image: androidsdk/android-30
before_script:
  - echo $KEYSTORE | base64 -d > app/chat_keystore.jks
  - echo $FIREBASE_CREDENCIAL_FILE_APP_CHAT | base64 -d > app/firebase_service_distribuition.json
  - echo $SERVICE_ACCOUNT_PLAY_CONSOLE_APP_CHAT | base64 -d > app/service_account_play_console.json
cache:
  key: gradlew
  paths:
    - ~./gradle/caches
    - ~./gradle/wrapper

stages:
  - Test
  - Build
  - DeployTest
  - PlayStore

Environment:
  stage: Test
  script:
    - cd app
    - ls -lla
    - cd ..
    - ./gradlew assembleRelease

Lint:
  stage: Test
  script:
    - ./gradlew lint

Klint:
  stage: Test
  script:
    - ./gradlew lintKotlin
Detekt:
  stage: Test
  script:
    - ./gradlew detekt

Sonarqube:
  stage: Test
  script:
    - ./gradlew build sonarqube

UnitAndInstrumentalTest:
  stage: Test
  script:
    - ./gradlew test

DebugAPK:
  stage: Build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/apk/**

ReleaseAPK:
  stage: Build
  script:
    - ./gradlew assembleRelease
  artifacts:
    paths:
      - app/build/outputs/apk/**

Firebase:
  stage: DeployTest
  script:
    - ./gradlew assembleRelease
    - ./gradlew appDistributionUploadRelease

internal:
  stage: DeployTest
  script:
    - ./gradlew assembleRelease
    - ./gradlew publishBundle


#Alpha:
#  stage: PlayStore
#  script:
#    - ./gradlew assembleRelease
#    - ./gradlew promoteArtifact --promote-track alpha
