image: androidsdk/android-30
before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
cache:
  key: gradlew
  paths:
    - ~./gradle/caches
    - ~./gradle/wrapper

stages:
  - Test
  - Build
  - DeployTest
  - PlayStore

Environment:
  stage: Test
  environment: test1
  script:
    - ./gradlew lint

Lint:
  stage: Test
  environment: test2
  script:
    - ./gradlew test
#
#Klint:
#  script:
#    -echo "Klint"
#Detekt:
#  script:
#    -echo "detek"
#
#Sonarqube:
#  script:
#    -echo "sonar"
#
#unitTest:
#  script:
#    -echo "unitTest"
#
DebugAPK:
  stage: Build
  environment: apk
  when: manual
  script:
    - ./gradlew assembleRelease
  artifacts:
    paths:
      - app/build/outputs/apk/**

ReleaseAPK:
  stage: Build
  environment: apk
  when: manual
  script:
    - ./gradlew assembleRelease
  artifacts:
    paths:
      - app/build/outputs/apk/**

#apk:
#  script:
#    -echo "IntrumentalTest"
#
#
#firebase:
#  script:
#    -echo "IntrumentalTest"
#
#
#appcenter:
#  script:
#    -echo "IntrumentalTest"
#
#
#internal:
#  script:
#    -echo "IntrumentalTest"
#
#
#alpha:
#  script:
#    -echo "IntrumentalTest"
