image: androidsdk/android-30
before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
cache:
  key: gradlew
  paths:
    - ~./gradle/caches
    - ~./gradle/wrapper

stages:
  - lint
  - test
  - build
  - firebase
  - internal
  - alpha
lint:
  stage: test
  environment: test1
  script:
    - ./gradlew lint

test:
  stage: test
  environment: test2
  script:
    - ./gradlew test
#
#klint:
#  script:
#    -echo "Klint"
#detekt:
#  script:
#    -echo "detek"
#
#sonarqube:
#  script:
#    -echo "sonar"
#
#unitTest:
#  script:
#    -echo "unitTest"
#
#IntrumentalTest:
#  script:
#    -echo "IntrumentalTest"

Build:
  stage: build
  environment: apk
  when: manual
  script:
    - ./gradlew assembleRelease
  artifacts:
    paths:
      - app/build/outputs/apk/**


#apk:
#  script:
#    -echo "IntrumentalTest"
#
#
#firebase:
#  script:
#    -echo "IntrumentalTest"
#
#
#appcenter:
#  script:
#    -echo "IntrumentalTest"
#
#
#internal:
#  script:
#    -echo "IntrumentalTest"
#
#
#alpha:
#  script:
#    -echo "IntrumentalTest"
