image: androidsdk/android-30

pipelines:
  custom:
    testgruop:
      - step:
          script:
            - ./gradlew detekt
            - ./gradlew lintKotlin
            - ./gradlew lint
            - ./gradlew sonarqube
  branches:
    master:
      - step:
          name: Configuring Environment
          caches:
            - gradle
          script:
            - echo $FIREBASE_CREDENCIAL_FILE_APP_CHAT | base64 -decode > app/firebase_service_distribuition.json
            - echo $SERVICE_ACCOUNT_PLAY_CONSOLE_APP_CHAT | base64 -decode > app/service_account_play_console.json
      - step:
          name: Build App
          caches:
            - gradle
            - gradle-wrapper
          script:
            - ./gradlew assembleDebug
          artifacts:
            - app/build/outputs/**
    development:
      - step:
          name: Define Envolvirement
          caches:
            - gradle
            - gradle/wrapper
          script:
            - base64 -d
          artifacts:
            - app/build/outputs/**
    release/*:
      - step:
          name: Define Envolvirement
          caches:
            - gradle
            - gradle/wrapper
          script:
            - base64 -d
          artifacts:
            - app/build/outputs/**
    feature/*:
      - step:
          name: Define Envolvirement
          caches:
            - gradle
            - gradle/wrapper
          script:
            - base64 -d
          artifacts:
            - app/build/outputs/**
    default:
      - step:
          name: Define Envolvirement
          caches:
            - gradle
            - gradle/wrapper
          script:
            - base64 -d
          artifacts:
            - app/build/outputs/**

definitions:
  caches:
    gradle-wrapper:
      ~/.gradle/wrapper/