image: androidsdk/android-30

pipelines:
  custom:
    testgruop:
      - step:
          script:
            - ./gradlew detekt
            - ./gradlew lintKotlin
            - ./gradlew lint
            - ./gradlew sonarqube
  branches:
    master:
      - step:
          name: Build App
          image: atlassian/default-image:latest
          caches:
            - gradle
            - gradle-wrapper
          script:
            - sudo apt-get update
            - sudo apt-get -y upgrade
            - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
            - wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O - | sudo apt-key add -
            - sudo apt-get -y install postgresql postgresql-contrib
            - sudo systemctl start postgresql
            - sudo systemctl enable postgresql
            - su - postgres
            - createuser sonar
            - psql
            - ALTER USER sonar WITH ENCRYPTED password '12345678';
            - \q
            - exit
            - wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.3.zip
            - apt-get -y install unzip
            - sudo unzip sonarqube-7.3.zip -d /opt
            - sudo mv /opt/sonarqube-7.3 /opt/sonarqube
            - sudo chown -R administrator:administrator /opt/sonarqube/
            - ./gradlew assembleDebug
            - ./gradlew lint
            - ./gradlew lintKotlin
            - ./gradlew detekt
            - ./gradlew sonar
            - ./gradlew testDebugUnitTest
            - ./gradlew assembleRelease
          artifacts:
            - app/build/outputs/**
#      - step:
#          name: lint
#          caches:
#            - gradle
#            - gradle-wrapper
#          script:
#            - ./gradlew lint
#          artifacts:
#            - app/build/reports/**
#      - step:
#          name: Ktlint
#          caches:
#            - gradle
#            - gradle-wrapper
#          script:
#            - ./gradlew lintKotlin
#      - step:
#          name: detekt
#          caches:
#            - gradle
#            - gradle-wrapper
#          script:
#            - ./gradlew detekt
#      - step:
#          name: sonarqube
#          caches:
#            - gradle
#            - gradle-wrapper
#          script:
#            - ./gradlew sonar
#      - step:
#          name: Unit Test
#          caches:
#            - gradle
#            - gradle-wrapper
#          script:
#            - ./gradlew testDebugUnitTest
#      - step:
#          name: Instrumental Test
#          caches:
#            - gradle
#            - gradle-wrapper
#          script:
#            - ./gradlew testDebugUnitTest
      - step:
          name: Deploy firebase
          trigger: manual
          script:
            - ./gradlew assembleRelease appDistributionUploadRelease
      - step:
          name: Deploy play console
          trigger: manual
          script:
            - ./gradlew assembleRelease publishBundle
definitions:
  caches:
    gradle-wrapper:
      ~/.gradle/wrapper/