image: androidsdk/android-30
definitions:
  steps: &build-step
    - step:
        name: SonarQube analysis
        image: sonarsource/sonar-scanner-cli:latest
        caches:
          - sonar
        script:
          - sonar-scanner
  caches:
    sonar: /opt/sonar-scanner/.sonar
    gradle-wrapper: ~/.gradle/wrapper/

clone:
  depth: full
pipelines:
  custom:
    testgruop:
      - step:
          script:
            - ./gradlew detekt
            - ./gradlew lintKotlin
            - ./gradlew lint
            - ./gradlew sonarqube
  branches:
    master:
      - step:
          name: Build App
          image: androidsdk/android-30
          caches:
            - gradle
            - gradle-wrapper
          script:
            - ./gradlew assembleDebug
            - ./gradlew lint
            - ./gradlew lintKotlin
            - ./gradlew detekt
            - ./gradlew build sonarqube
            - ./gradlew testDebugUnitTest
            - ./gradlew assembleRelease
          artifacts:
            - app/build/outputs/**
#      - step:
#          name: lint
#          caches:
#            - gradle
#            - gradle-wrapper
#          script:
#            - ./gradlew lint
#          artifacts:
#            - app/build/reports/**
#      - step:
#          name: Ktlint
#          caches:
#            - gradle
#            - gradle-wrapper
#          script:
#            - ./gradlew lintKotlin
#      - step:
#          name: detekt
#          caches:
#            - gradle
#            - gradle-wrapper
#          script:
#            - ./gradlew detekt
#      - step:
#          name: sonarqube
#          caches:
#            - gradle
#            - gradle-wrapper
#          script:
#            - ./gradlew sonar
#      - step:
#          name: Unit Test
#          caches:
#            - gradle
#            - gradle-wrapper
#          script:
#            - ./gradlew testDebugUnitTest
#      - step:
#          name: Instrumental Test
#          caches:
#            - gradle
#            - gradle-wrapper
#          script:
#            - ./gradlew testDebugUnitTest
      - step:
          name: Deploy firebase
          trigger: manual
          script:
            - ./gradlew assembleRelease appDistributionUploadRelease
      - step:
          name: Deploy play console
          trigger: manual
          script:
            - ./gradlew assembleRelease publishBundle

