image: androidsdk/android-30

pipelines:
  branches:
    master:
      - step:
          name: Build
          caches:
            - gradle
            - gradle/wrapper
          script:
            - ./gradlew assembleDebug
          artifacts:
            - app/build/outputs/**
