image: androidsdk/android-30

pipelines:
  custom:
    testgruop:
      - step:
          script:
            - ./gradlew detekt
            - ./gradlew lintKotlin
            - ./gradlew lint
            - ./gradlew sonarqube
  branches:
    master:
      - step:
          name: Build App
          caches:
            - gradle
            - gradle-wrapper
          script:
            - ./gradlew assembleDebug
          artifacts:
            - app/build/outputs/**
      - step:
          name: lint
          caches:
            - gradle
            - gradle-wrapper
          script:
            - ./gradlew lint
          artifacts:
            - app/build/reports/**
      - step:
          name: Ktlint
          caches:
            - gradle
            - gradle-wrapper
          script:
            - ./gradlew lintKotlin
      - step:
          name: detekt
          caches:
            - gradle
            - gradle-wrapper
          script:
            - ./gradlew detekt
#      - step:
#          name: sonarqube
#          caches:
#            - gradle
#            - gradle-wrapper
#          script:
#            - ./gradlew sonar
      - step:
          name: Unit Test
          caches:
            - gradle
            - gradle-wrapper
          script:
            - ./gradlew ./gradlew testDebugUnitTest
      - step:
          name: Deploy firebase
          trigger: manual
          script:
            - ./gradlew assembleRelease appDistributionUploadRelease
      - step:
          name: Deploy play console
          trigger: manual
          script:
            - ./gradlew assembleRelease publishBundle
    development:
      - step:
          name: Define Envolvirement
          caches:
            - gradle
            - gradle/wrapper
          script:
            - base64 -d
          artifacts:
            - app/build/outputs/**
    release/*:
      - step:
          name: Define Envolvirement
          caches:
            - gradle
            - gradle/wrapper
          script:
            - base64 -d
          artifacts:
            - app/build/outputs/**
    feature/*:
      - step:
          name: Define Envolvirement
          caches:
            - gradle
            - gradle/wrapper
          script:
            - base64 -d
          artifacts:
            - app/build/outputs/**
    default:
      - step:
          name: Define Envolvirement
          caches:
            - gradle
            - gradle/wrapper
          script:
            - base64 -d
          artifacts:
            - app/build/outputs/**

definitions:
  caches:
    gradle-wrapper:
      ~/.gradle/wrapper/