name: Push Feature

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - feature/*

jobs:
  build-debug-apk-feature:
    runs-on: ubuntu-latest
    environment: BUILD-FEATURE
    container:
      image: androidsdk/android-30
    steps:
      - uses: actions/checkout@v3
      - name: Setup Environment
        env :
          APP_ID: ${{secrets.APP_CHAT_ID_FIREBASE}}
        run: |
          export APP_CHAT_ID_FIREBASE=$APP_ID

      - name: Build Debug Apk
        run: ./gradlew assembleDebug

      - name: Upload Apk Debug
        uses: actions/upload-artifact@v3
        with:
          name: debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk

  build-release-apk-feature:
    runs-on: ubuntu-latest
    environment: BUILD-FEATURE
    container:
      image: androidsdk/android-30
    steps:
      - uses: actions/checkout@v3
      - name: Setup Environment
        env:
          APP_ID: ${{secrets.APP_CHAT_ID_FIREBASE}}
          KEYSTORE_APP: ${{secrets.KEYSTORE}}
          FIREBASE_APP: ${{secrets.FIREBASE}}
          SERVICE_ACCOUNT_APP: ${{secrets.SERVICE_ACCOUNT}}
        run: |
          export APP_CHAT_ID_FIREBASE=$APP_ID
          echo $KEYSTORE_APP | base64 -d > app/chat_keystore.jks
          echo $FIREBASE_APP | base64 -d > app/firebase_service_distribuition.json
          echo $SERVICE_ACCOUNT_APP | base64 -d > app/service_account_play_console.json
      - name: Build Release Apk
        run: ./gradlew assembleRelease

      - name: Upload Apk Release
        uses: actions/upload-artifact@v3
        with:
          name: release.apk
          path: app/build/outputs/apk/release/app-release.apk

  Lint:
    needs:
      - build-release-apk-feature
      - build-debug-apk-feature
    runs-on: ubuntu-latest
    environment: TEST-FEATURE
    container:
      image: androidsdk/android-30

    steps:
      - uses: actions/checkout@v3

      - name: Lint Test
        run: ./gradlew lint

      - name: Upload result lint Test
        uses: actions/upload-artifact@v3
        with:
          name: index.html
          path: app/build/reports/lint-results-debug.html

  Intrumental-and-Unit-Test:
    needs:
      - build-release-apk-feature
      - build-debug-apk-feature
    runs-on: ubuntu-latest
    environment: TEST-FEATURE
    container:
      image: androidsdk/android-30
    steps:
      - uses: actions/checkout@v3
      - name: Setup Environment
        env:
          APP_ID: ${{secrets.APP_CHAT_ID_FIREBASE}}
          KEYSTORE_APP: ${{secrets.KEYSTORE}}
        run: |
          export APP_CHAT_ID_FIREBASE=$APP_ID
          echo $KEYSTORE_APP | base64 -d > app/chat_keystore.jks

      - name: Unit Test
        run: ./gradlew test

      - name: Upload result Instrumental and Unit test
        uses: actions/upload-artifact@v3
        with:
          name: index.html
          path: app/build/reports/tests/testDebugUnitTest/index.html
