name: Push CI

on:
  push:
    branches:
      - feature/*
      - release/app-[0-9]+.[0-9]+.[0-9]
      - master
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: androidsdk/android-30
    steps:
      - uses: actions/checkout@v3
      - name: environment variable
        env:
          APPID: ${{secrets.APP_CHAT_ID_FIREBASE}}
          KEYSTORE: ${{secrets.KEYSTORE_PROPERTIES_FILE_APP_CHAT}}
          FIREBASE: ${{secrets.KEYSTORE_PROPERTIES_FILE_APP_CHAT}}
        run: |
          echo $APPID | export APP_CHAT_ID_FIREBASE=$APPID,
          echo $KEYSTORE | base64 -d > app/keystore.properties,
          cd app/,
          ls -lla,
          cd ..,
          echo $FIREBASE | base64 -d > app/firebase_service_distribuition.json,
          cd app,
          ls -lal,
          cd ..,
          echo $PLAYCONSOLE | base64 -d > app/service_account_play_console.json,
          cd app,
          ls -lal,
          cd ..,
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
  test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: androidsdk/android-30
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Lint Test
        run: ./gradlew lintDebug

      - name: Upload html lint test Report
        uses: actions/upload-artifact@v3
        with:
          name: index.html
          path: app/build/reports/lint-results-debug.html

      - name: Ktlint Test
        run: ./gradlew lintKotlin

      - name: Detekt Test
        run: ./gradlew detekt

      - name: Sonarqube Test
        run: ./gradlew sonarqube

      - name: Unit Test
        run: ./gradlew testDebugUnitTest

      - name: Build with Gradle
        run: ./gradlew build

  apk:
    needs: test
    runs-on: ubuntu-latest
    container:
      image: androidsdk/android-30
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate Apk
        run: ./gradlew assembleDebug

      - name: Upload Apk
        uses: actions/upload-artifact@v3
        with:
          name: debug.apk
          path: app/build/outputs/**