name: Push Master
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: androidsdk/android-30
    steps:
      - uses: actions/checkout@v3
      - name: Generate Keystore
        run: echo $KEYSTORE_PROPERTIES_FILE_APP_CHAT | base64 -d > app/chat_keystore.jks
      - name: Firebase Config
        run: echo $FIREBASE_CREDENCIAL_FILE_APP_CHAT | base64 -d > app/firebase_service_distribuition.json
      - name: Generate Account Service
        run: echo $SERVICE_ACCOUNT_PLAY_CONSOLE_APP_CHAT | base64 -d > app/service_account_play_console.json
      - name: AppId fir
        run: export appIdFirebaseAppChat=$APP_CHAT_ID_FIREBASE
      - name: Debug Version Apk
        run: ./gradlew assembleDebug
      - name: Release Version Apk
        run: ./gradlew assembleRelease
#  test:
#    needs: build
#    runs-on: ubuntu-latest
#    container:
#      image: androidsdk/android-30
#    steps:
#      - uses: actions/checkout@v3
#      - name: set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#          cache: gradle
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#
#      - name: Lint Test
#        run: ./gradlew lintDebug
#
#      - name: Upload html lint test Report
#        uses: actions/upload-artifact@v3
#        with:
#          name: index.html
#          path: app/build/reports/lint-results-debug.html
#
#      - name: Ktlint Test
#        run: ./gradlew lintKotlin
#
#      - name: Detekt Test
#        run: ./gradlew detekt
#
#      - name: Sonarqube Test
#        run: ./gradlew sonarqube
#
#      - name: Unit Test
#        run: ./gradlew testDebugUnitTest
#
#      - name: Build with Gradle
#        run: ./gradlew build

#  apk:
#    needs: test
#    runs-on: ubuntu-latest
#    container:
#      image: androidsdk/android-30
#    steps:
#      - uses: actions/checkout@v3
#      - name: set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#          cache: gradle
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#
#      - name: Generate Apk
#        run: ./gradlew assembleDebug
#
#      - name: Upload Apk
#        uses: actions/upload-artifact@v3
#        with:
#          name: debug.apk
#          path: app/build/outputs/**