name: Push Master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-release-apk:
    runs-on: ubuntu-latest
    environment: production
    container:
      image: androidsdk/android-30
    steps:
      - uses: actions/checkout@v3
      - name: Setup Environment
        env :
          APP_ID: ${{secrets.APP_CHAT_ID_FIREBASE}}
        run: |
          export APP_CHAT_ID_FIREBASE=$APP_ID

      - name: Build Debug Apk
        run: ./gradlew assembleDebug

      - name: Upload Apk Debug
        uses: actions/upload-artifact@v3
        with:
          name: debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk

  build-debug-apk:
    runs-on: ubuntu-latest
      environment: production
      container:
        image: androidsdk/android-30
      steps:
        - uses: actions/checkout@v3
        - name: Setup Environment
          env:
            APP_ID: ${{secrets.APP_CHAT_ID_FIREBASE}}
            KEYSTORE_APP: ${{secrets.KEYSTORE}}
            FIREBASE_APP: ${{secrets.FIREBASE}}
            SERVICE_ACCOUNT_APP: ${{secrets.SERVICE_ACCOUNT}}
          run: |
            export APP_CHAT_ID_FIREBASE=$APP_ID
            echo $KEYSTORE_APP | base64 -d > app/chat_keystore.jks
            echo $FIREBASE_APP | base64 -d > app/firebase_service_distribuition.json
            echo $SERVICE_ACCOUNT_APP | base64 -d > app/service_account_play_console.json

        - name: Build Release Apk
          run: ./gradlew assembleRelease

        - name: Upload Apk Release
          uses: actions/upload-artifact@v3
          with:
            name: release.apk
            path: app/build/outputs/apk/release/app-release.apk
  test-code:
    needs: build-apk
    runs-on: ubuntu-latest
    container:
      image: androidsdk/android-30
    steps:
      - uses: actions/checkout@v3
      - name: Setup Environment
        env :
          APP_ID: ${{secrets.APP_CHAT_ID_FIREBASE}}
          KEYSTORE_APP: ${{secrets.KEYSTORE}}
          FIREBASE_APP: ${{secrets.FIREBASE}}
          SERVICE_ACCOUNT_APP: ${{secrets.SERVICE_ACCOUNT}}
        run: |
          export APP_CHAT_ID_FIREBASE=$APP_ID
          echo $KEYSTORE_APP | base64 -d > app/chat_keystore.jks
          echo $FIREBASE_APP | base64 -d > app/firebase_service_distribuition.json
          echo $SERVICE_ACCOUNT_APP | base64 -d > app/service_account_play_console.json

      - name: Lint Test
        run: ./gradlew lint

      - name: Upload result lint Test
        uses: actions/upload-artifact@v3
        with:
          name: index.html
          path: app/build/reports/lint-results-debug.html

      - name: Ktlint Test
        run: ./gradlew lintKotlin

      - name: Upload result ktlint test
        uses: actions/upload-artifact@v3
        with:
          name: Ktlint
          path: app/build/reports/ktlint/**

      - name: Detekt Test
        run: ./gradlew detekt

      - name: Upload result detekt test
        uses: actions/upload-artifact@v3
        with:
          name: ResultDetekt
          path: app/build/reports/detekt/detekt/detekt.html

      - name: Sonarqube Test
        run: ./gradlew sonar

      - name: Upload result Sonarqube test
        uses: actions/upload-artifact@v3
        with:
          name: sonarqube
          path: app/build/sonar/**

      - name: Unit Test
        run: ./gradlew test

      - name: Upload result Instrumental and Unit test
        uses: actions/upload-artifact@v3
        with:
          name: index.html
          path: app/build/reports/tests/testDebugUnitTest/index.html



#  apk:
#    needs: test
#    runs-on: ubuntu-latest
#    container:
#      image: androidsdk/android-30
#    steps:
#      - uses: actions/checkout@v3
#      - name: set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#          cache: gradle
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#
#      - name: Generate Apk
#        run: ./gradlew assembleDebug
#
#      - name: Upload Apk
#        uses: actions/upload-artifact@v3
#        with:
#          name: debug.apk
#          path: app/build/outputs/**